export const BIOMETRIC_LOGIN = 'BIOMETRIC_LOGIN';
export const BIOMETRIC_TRANSACTION = 'BIOMETRIC_TRANSACTION';
export const APP_NOTIFICATIONS = 'APP_NOTIFICATIONS';
export const APP_VERSION = 'APP_VERSION';
export const APP_UPDATING = 'APP_UPDATING';
export const SET_DEEPLINK_PATH = 'SET_DEEPLINK_PATH';
export const CLEAR_DEEPLINK_PATH = 'CLEAR_DEEPLINK_PATH';
