export const TOUR_DONE = 'TOUR_DONE';

export const AUTH_DATA = 'AUTH_DATA';


export const USER_DATA = 'USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const ADD_REFERAL = 'ADD_REFERAL';


export const START_REFERAL_CODE = 'START_REFERAL_CODE';
export const START_REFERAL_CODE_FAILED = 'START_REFERAL_CODE_FAILED';
export const LOAD_REFERAL_CODE = 'LOAD_REFERAL_CODE';



export const USER_PWD = 'USER_PWD';
export const CLEAR_USER_PWD = 'CLEAR_USER_PWD';

export const USER_PIN = 'USER_PIN';
export const CLEAR_USER_PIN = 'CLEAR_USER_PIN';

export const START_LOAD_PROFILE = 'START_LOAD_PROFILE';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_FAILED = 'LOAD_PROFILE_FAILED';

export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const RESET_APPLICATION = 'RESET_APPLICATION';

export const REGISTER_SESSION_PROMPT = 'REGISTER_SESSION_PROMPT';
export const CLEAR_SESSION_PROMPT = 'CLEAR_SESSION_PROMPT';

export const SHOW_SESSION_DIALOG = 'SHOW_SESSION_DIALOG';
export const HIDE_SESSION_DIALOG = 'HIDE_SESSION_DIALOG';

export const START_LOAD_PREFERENCES = 'START_LOAD_PREFERENCES';
export const LOAD_PREFERENCES = 'LOAD_PREFERENCES';
export const LOAD_PREFERENCES_FAILED = 'LOAD_PREFERENCES_FAILED';

export const START_LOAD_REFERRAL_ACTIVITIES = 'START_LOAD_REFERRAL_ACTIVITIES';
export const LOAD_REFERRAL_ACTIVITIES = 'LOAD_REFERRAL_ACTIVITIES';
export const LOAD_REFERRAL_ACTIVITIES_FAILED = 'LOAD_REFERRAL_ACTIVITIES_FAILED';

export const SHOW_SCREEN_INACTIVITY_DIALOG = 'SHOW_SCREEN_INACTIVITY_DIALOG';
export const HIDE_SCREEN_INACTIVITY_DIALOG = 'HIDE_SCREEN_INACTIVITY_DIALOG';

