// STATUS BAR STYLES
export const BLUE_STATUS_BAR = 'BLUE_STATUS_BAR';
export const TRANSLUCENT_STATUS_BAR = 'TRANSLUCENT_STATUS_BAR';
export const WHITE_STATUS_BAR = 'WHITE_STATUS_BAR';
export const ASH_STATUS_BAR = 'ASH_STATUS_BAR';
export const ORANGE_STATUS_BAR = 'ORANGE_STATUS_BAR';