export const UPDATE_BILL_PAYMENT = 'UPDATE_BILL_PAYMENT';
export const RESET_BILL_PAYMENT = 'RESET_BILL_PAYMENT';

export const START_LOAD_BILLER_CATEGORIES = 'START_LOAD_BILLER_CATEGORIES';
export const LOAD_BILLER_CATEGORIES = 'LOAD_BILLER_CATEGORIES';
export const BILLER_CATEGORIES_FAILED = 'BILLER_CATEGORIES_FAILED';