export const START_LOAD_DROPDOWN = 'START_LOAD_DROPDOWN';
export const LOAD_DROPDOWN = 'LOAD_DROPDOWN';
export const LOAD_DROPDOWN_FAILED = 'LOAD_DROPDOWN_FAILED';

export const START_LOAD_BANKS = 'START_LOAD_BANKS';
export const LOAD_BANKS = 'LOAD_BANKS';
export const LOAD_BANKS_FAILED = 'LOAD_BANKS_FAILED';

export const START_LOAD_STATES = 'START_LOAD_STATES';
export const LOAD_STATES = 'LOAD_STATES';
export const LOAD_STATES_FAILED = 'LOAD_STATES_FAILED';

export const START_LOAD_LGA = 'START_LOAD_LGA';
export const LOAD_LGA = 'LOAD_LGA';
export const LOAD_LGA_FAILED = 'LOAD_LGA_FAILED';