export const START_LOAD_LOAN_PRODUCTS = 'START_LOAD_LOAN_PRODUCTS';
export const LOAD_LOAN_PRODUCTS = 'LOAD_LOAN_PRODUCTS';
export const LOAD_LOAN_PRODUCTS_FAILED = 'LOAD_LOAN_PRODUCTS_FAILED';

export const START_LOAD_SCORING_OPTIONS = 'START_LOAD_SCORING_OPTIONS';
export const LOAD_SCORING_OPTIONS = 'LOAD_SCORING_OPTIONS';
export const LOAD_SCORING_OPTIONS_FAILED = 'LOAD_SCORING_OPTIONS_FAILED';

export const START_LOAD_LOAN_REASONS = 'START_LOAD_LOAN_REASONS';
export const LOAD_LOAN_REASONS = 'LOAD_LOAN_REASONS';
export const LOAD_LOAN_REASONS_FAILED = 'LOAD_LOAN_REASONS_FAILED';

export const START_LOAD_USER_LOANS = 'START_LOAD_USER_LOANS';
export const LOAD_USER_LOANS = 'LOAD_USER_LOANS';
export const LOAD_USER_LOANS_FAILED = 'LOAD_USER_LOANS_FAILED';