export const START_LOAD_NOTIFICATIONS = 'START_LOAD_NOTIFICATIONS';
export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
export const LOAD_NOTIFICATIONS_FAILED = 'LOAD_NOTIFICATIONS_FAILED';

export const SAVE_NOTIFICATION = 'SAVE_NOTIFICATION';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';