export const START_LOAD_CARDS = 'START_LOAD_CARDS';
export const LOAD_CARDS = 'LOAD_CARDS';
export const LOAD_CARDS_FAILED = 'LOAD_CARDS_FAILED';
export const START_LOAD_ACCOUNTS = 'START_LOAD_ACCOUNTS';
export const LOAD_ACCOUNTS = 'LOAD_ACCOUNTS';
export const LOAD_ACCOUNTS_FAILED = 'LOAD_ACCOUNTS_FAILED';
