export const START_LOAD_SAVINGS_PRODUCTS = 'START_LOAD_SAVINGS_PRODUCTS';
export const LOAD_SAVINGS_PRODUCTS = 'LOAD_SAVINGS_PRODUCTS';
export const LOAD_SAVINGS_PRODUCTS_FAILED = 'LOAD_SAVINGS_PRODUCTS_FAILED';

export const START_LOAD_SAVINGS_COLLECT_MODES = 'START_LOAD_SAVINGS_COLLECT_MODES';
export const LOAD_SAVINGS_COLLECT_MODES = 'LOAD_SAVINGS_COLLECT_MODES';
export const LOAD_SAVINGS_COLLECT_MODES_FAILED = 'LOAD_SAVINGS_COLLECT_MODES_FAILED';

export const START_LOAD_SAVINGS_FREQUENCIES = 'START_LOAD_SAVINGS_FREQUENCIES';
export const LOAD_SAVINGS_FREQUENCIES = 'LOAD_SAVINGS_FREQUENCIES';
export const LOAD_SAVINGS_FREQUENCIES_FAILED = 'LOAD_SAVINGS_FREQUENCIES_FAILED';

export const START_LOAD_USER_SAVINGS = 'START_LOAD_USER_SAVINGS';
export const LOAD_USER_SAVINGS = 'LOAD_USER_SAVINGS';
export const LOAD_USER_SAVINGS_FAILED = 'LOAD_USER_SAVINGS_FAILED';

export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const RESET_APPLICATION = 'RESET_APPLICATION';
export const UPDATE_SAVINGS_ARCHIVED_STATUS = 'UPDATE_SAVINGS_ARCHIVED_STATUS';