export const UPDATE_FUNDS_TRANSFER = 'UPDATE_FUNDS_TRANSFER';
export const RESET_FUNDS_TRANSFER = 'RESET_FUNDS_TRANSFER';

export const START_LOAD_BENEFICIARIES = 'START_LOAD_BENEFICIARIES';
export const LOAD_BENEFICIARIES = 'LOAD_BENEFICIARIES';
export const LOAD_BENEFICIARIES_FAILED = 'LOAD_BENEFICIARIES_FAILED';

export const UPDATE_RECENT_TRANSFERS = 'UPDATE_RECENT_TRANSFERS';
export const UPDATE_ACCOUNT_TYPE = 'UPDATE_ACCOUNT_TYPE';


