export const START_LOAD_USER_WALLET = 'START_LOAD_USER_WALLET';
export const LOAD_USER_WALLET = 'LOAD_USER_WALLET';
export const LOAD_USER_WALLET_FAILED = 'LOAD_USER_WALLET_FAILED';

export const START_LOAD_WALLET_TRANSACTIONS = 'START_LOAD_WALLET_TRANSACTIONS';
export const LOAD_WALLET_TRANSACTIONS = 'LOAD_WALLET_TRANSACTIONS';
export const LOAD_WALLET_TRANSACTIONS_FAILED = 'LOAD_WALLET_TRANSACTIONS_FAILED';

export const START_LOAD_WALLET_TRANSACTIONS_DEBIT = 'START_LOAD_WALLET_TRANSACTIONS_DEBIT';
export const LOAD_WALLET_TRANSACTIONS_DEBIT = 'LOAD_WALLET_TRANSACTIONS_DEBIT';
export const LOAD_WALLET_TRANSACTIONS_DEBIT_FAILED = 'LOAD_WALLET_TRANSACTIONS_DEBIT_FAILED';

export const START_LOAD_WALLET_TRANSACTIONS_CREDIT = 'START_LOAD_WALLET_TRANSACTIONS_CREDIT';
export const LOAD_WALLET_TRANSACTIONS_CREDIT = 'LOAD_WALLET_TRANSACTIONS_CREDIT';
export const LOAD_WALLET_TRANSACTIONS_CREDIT_FAILED = 'LOAD_WALLET_TRANSACTIONS_CREDIT_FAILED';
